# Generated by Django 4.0.1 on 2022-01-19 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('des', models.TextField(blank=True, null=True, verbose_name='Descriptions')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date')),
            ],
        ),
    ]
